services:
  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: ["/bin/bash", "-c", "bash /app/entrypoint.sh"]
    restart: unless-stopped

  worker:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "app.workers.celery_app.celery_app", "worker", "--loglevel=INFO"]
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
